frontend:
  paths:
    - 'frontend/**'
    - 'src/routers/**'

backend:
  paths:
    - 'backend/**'
    - 'src/new.py'
    - 'src/new/**'

bot:
  paths:
    - 'bot/**'
    - 'src/app.py'
    - 'src/app/**'

docs:
  paths:
    - '**/*.md'
    - 'docs/**'

config:
  paths:
    - '.github/**'
    - '**/*.yml'
    - '**/*.yaml'

tests:
  paths:
    - 'tests/**'
    - '**/*_test.py'
